# Generated by Django 4.1.7 on 2023-03-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizzes",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
